/**
*
* @licstart  The following is the entire license notice for the JavaScript code in this file.
*
* Tasks microservice of Identifier Services
*
* Copyright (C) 2019 University Of Helsinki (The National Library Of Finland)
*
* This file is part of identifier-services-tasks
*
* identifier-services-tasks program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
*
* identifier-services-tasks is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
*
* You should have received a copy of the GNU Affero General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
*
* @licend  The above is the entire license notice
* for the JavaScript code in this file.
*
*/

import startApp from './app';
import {
	MONGO_URI,
	TZ,
	MAX_CONCURRENCY,
	JOB_STATE,
	JOB_TYPE,
	JOB_SUB_TYPE,
	JOB_FREQ_PENDING,
	JOB_FREQ_IN_PROGRESS,
	JOB_FREQ_REQUEST_STATE_NEW,
	JOB_FREQ_REQUEST_STATE_ACCEPTED,
	JOB_FREQ_REQUEST_STATE_REJECTED,
	JOB_USER_REQUEST_STATE_NEW,
	JOB_USER_REQUEST_STATE_ACCEPTED,
	JOB_USER_REQUEST_STATE_REJECTED,
	JOB_PUBLISHER_REQUEST_STATE_NEW,
	JOB_PUBLISHER_REQUEST_STATE_ACCEPTED,
	JOB_PUBLISHER_REQUEST_STATE_REJECTED,
	JOB_PUBLICATION_ISBNISMN_REQUEST_STATE_NEW,
	JOB_PUBLICATION_ISBNISMN_REQUEST_STATE_ACCEPTED,
	JOB_PUBLICATION_ISBNISMN_REQUEST_STATE_REJECTED,
	JOB_PUBLICATION_ISSN_REQUEST_STATE_NEW,
	JOB_PUBLICATION_ISSN_REQUEST_STATE_ACCEPTED,
	JOB_PUBLICATION_ISSN_REQUEST_STATE_REJECTED,
	JOB_BIBLIOGRAPHIC_METADATA_PENDING,
	JOB_BIBLIOGRAPHIC_METADATA_INPROGRESS,
	REQUEST_TTL,
	JOB_REQUEST_BG_PROCESSING_CLEANUP_USERS,
	JOB_REQUEST_BG_PROCESSING_CLEANUP_PUBLISHERS,
	JOB_REQUEST_BG_PROCESSING_CLEANUP_ISBN_ISMN,
	JOB_REQUEST_BG_PROCESSING_CLEANUP_ISSN
} from './config';

startTask();

export default async function startTask() {
	return startApp({
		MONGO_URI,
		TZ,
		MAX_CONCURRENCY,
		JOB_STATE,
		JOB_TYPE,
		JOB_SUB_TYPE,
		JOB_FREQ_PENDING,
		JOB_FREQ_IN_PROGRESS,
		JOB_FREQ_REQUEST_STATE_NEW,
		JOB_FREQ_REQUEST_STATE_ACCEPTED,
		JOB_FREQ_REQUEST_STATE_REJECTED,
		JOB_USER_REQUEST_STATE_NEW,
		JOB_USER_REQUEST_STATE_ACCEPTED,
		JOB_USER_REQUEST_STATE_REJECTED,
		JOB_PUBLISHER_REQUEST_STATE_NEW,
		JOB_PUBLISHER_REQUEST_STATE_ACCEPTED,
		JOB_PUBLISHER_REQUEST_STATE_REJECTED,
		JOB_PUBLICATION_ISBNISMN_REQUEST_STATE_NEW,
		JOB_PUBLICATION_ISBNISMN_REQUEST_STATE_ACCEPTED,
		JOB_PUBLICATION_ISBNISMN_REQUEST_STATE_REJECTED,
		JOB_PUBLICATION_ISSN_REQUEST_STATE_NEW,
		JOB_PUBLICATION_ISSN_REQUEST_STATE_ACCEPTED,
		JOB_PUBLICATION_ISSN_REQUEST_STATE_REJECTED,
		JOB_BIBLIOGRAPHIC_METADATA_PENDING,
		JOB_BIBLIOGRAPHIC_METADATA_INPROGRESS,
		REQUEST_TTL,
		JOB_REQUEST_BG_PROCESSING_CLEANUP_USERS,
		JOB_REQUEST_BG_PROCESSING_CLEANUP_PUBLISHERS,
		JOB_REQUEST_BG_PROCESSING_CLEANUP_ISBN_ISMN,
		JOB_REQUEST_BG_PROCESSING_CLEANUP_ISSN
	});
}
